# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_auto_20170306_2116'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
    ]
